apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-claim
  labels:
    app: ftps
spec:
  storageClassName: ftps-volume
  selector:
    matchLabels:
      name: ftps-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        lifecycle:
          postStart:
            exec:
              command:
                - "chown"
                - "admin"
                - "/home/usr"
        image: ftpsdock:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: ftps-volume
          mountPath: /home/usr
      volumes:
      - name: ftps-volume
        persistentVolumeClaim:
          claimName: ftps-claim

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.254
  selector:
    app: ftps
  ports:
  - name: http
    port: 21
  - name: file-port
    port: 21021