apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers: 
      - name: wordpress
        image: wordpressdock:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
